2021-05-21 20:22:04,385 INFO    MainThread:131837 [wandb_setup.py:_flush():69] setting env: {}
2021-05-21 20:22:04,385 INFO    MainThread:131837 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-21 20:22:04,385 INFO    MainThread:131837 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Mask-Detection-PT-V2/wandb/run-20210521_202204-3a162dli/logs/debug.log
2021-05-21 20:22:04,385 INFO    MainThread:131837 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Mask-Detection-PT-V2/wandb/run-20210521_202204-3a162dli/logs/debug-internal.log
2021-05-21 20:22:04,385 INFO    MainThread:131837 [wandb_init.py:init():369] calling init triggers
2021-05-21 20:22:04,385 INFO    MainThread:131837 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-21 20:22:04,385 INFO    MainThread:131837 [wandb_init.py:init():418] starting backend
2021-05-21 20:22:04,385 INFO    MainThread:131837 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-21 20:22:04,415 INFO    MainThread:131837 [backend.py:ensure_launched():132] starting backend process...
2021-05-21 20:22:04,442 INFO    MainThread:131837 [backend.py:ensure_launched():137] started backend process with pid: 132027
2021-05-21 20:22:04,443 INFO    MainThread:131837 [wandb_init.py:init():423] backend started and connected
2021-05-21 20:22:04,446 INFO    MainThread:131837 [wandb_init.py:init():465] updated telemetry
2021-05-21 20:22:04,446 INFO    MainThread:131837 [wandb_init.py:init():484] communicating current version
2021-05-21 20:22:05,470 INFO    MainThread:131837 [wandb_init.py:init():489] got version response 
2021-05-21 20:22:05,471 INFO    MainThread:131837 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-21 20:22:06,088 INFO    MainThread:131837 [wandb_init.py:init():522] starting run threads in backend
2021-05-21 20:22:11,093 INFO    MainThread:131837 [wandb_run.py:_console_start():1565] atexit reg
2021-05-21 20:22:11,093 INFO    MainThread:131837 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-21 20:22:11,094 INFO    MainThread:131837 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-21 20:22:11,095 INFO    MainThread:131837 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-21 20:22:11,095 INFO    MainThread:131837 [wandb_init.py:init():546] run started, returning control to user process
2021-05-21 20:22:11,448 INFO    MainThread:131837 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-21 20:22:11,459 INFO    MainThread:131837 [wandb_run.py:_restore():1507] restore
2021-05-21 20:22:13,722 INFO    MainThread:131837 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
}
pusher_stats {
}

2021-05-21 20:22:14,317 INFO    MainThread:131837 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  other_count: 1
}
pusher_stats {
  total_bytes: 1552
}

2021-05-21 20:22:15,109 INFO    MainThread:131837 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 1552
  total_bytes: 18515
}

2021-05-21 20:22:15,765 INFO    MainThread:131837 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 9744
  total_bytes: 18515
}

2021-05-21 20:22:15,867 INFO    MainThread:131837 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 12663
  total_bytes: 18515
}

